### ISSUE TITLE
ALS developer team WIL ik Duidelijkheid krijgen van het domein/data storage solution

### ISSUE THREAD

**Issue by mobenna** [Kalipo-BV/kalipo-core#712]
# Research story specification 
ALS developer team WIL ik duidelijkheid krijgen van het domein/data storage sollution ZODAT wij deze informatie kunnen gebruiken bij het ontwikelen van de app

## Acceptance criteria
- [x] Er is duidelijk hoe de opslag naar de blockchain werkt
- [x] Er is duidelijk hoe de opslag naar een datastore werkt(sql database, nosql database, file)
- [x] Er is een voorbeeld functie om data op te slaan.
- [x] Er is een voorbeeld functie om opslag op te halen.

# DoR
*Een user story voldoet aan de DoR wanneer deze voldoet aan:*
- [x] Er is een front-end ontwikkel omgeving beschikbaar
- [x] Er is een remote development omgeving als backend
- [x] Er is toegang tot de repository.
- [x] taken/userstories zijn verdeeld.

## DoD
Een user story voldoet aan de DoD wanneer deze voldoet aan:

- [x] De stijl van Kalipo
- [ ] Gereviewd door de product owner en voldoet aan acceptatiecriteria
- [x] Er is een spellingscontrole gedaan
- [x] Er zijn peer-reviews geweest
- [x] Gedocumenteerd 

## Deliverables
- [x] Er is duidelijk gemaakt doormiddel van visuele schermen hoe het domein in elkaar zit.

## info
![image](https://user-images.githubusercontent.com/74923309/227879254-a481764e-4c1f-4d06-8ef6-e6df076490b0.png)
![image](https://user-images.githubusercontent.com/74923309/227879415-116348aa-fef1-47f8-b2ec-d4ed47c8898a.png)
![image](https://user-images.githubusercontent.com/74923309/227879524-21e8e72b-9605-4766-8e68-fdf0d8b9874e.png)
![image](https://user-images.githubusercontent.com/74923309/227879578-9a8b1146-26de-49b6-a47f-6836e779ffbf.png)
![image](https://user-images.githubusercontent.com/74923309/227879789-883f6bb5-2050-44bf-9762-0497e5d48dfc.png)

**Comment by Armaniimus** [comment]
userstory is klaar voor acceptence
