### ISSUE TITLE
Stakeholdergesprek met matthias

### ISSUE THREAD

**Issue by rubiertje** [Kalipo-BV/kalipo-core#779]
### Vragen Matthias:

**Hoe gaan we de klasse improvement proposal maken? losse klasse?**

**Wat houdt een provision in? (attribuut van proposal)**

**src -> app -> database -> action -> {file}**
- Wat wordt er in 'membership_invitation_actions' gedaan? want de klasse zegt dat het over de invitation gaat, alleen we zien iets in de process function met dat een proposal geaccepteerd wordt? Wat wordt hiermee gedaan? 
- Waarom wordt er bij Accepted en refused een 0 geset?

**src -> app -> modules -> proposal -> proposal_module.ts**
- Wat doet de functie initializeOrResetRowContexts()?
- afterBlockApply() -> Regel 108: Wat is het object index? (onder andere '.scheduled')

**Comment by Dave-nbg** [comment]
vragen Matthias:
- provision is de regels van de constitution
- is eigenlijk het aanmaken van de invite

- 0 is false en 1 is wat gekozen wordt

- wss geen probleem maar is voor indexen van ids
- schedule is iets wat ook in indices zit. Kijk in membership_invitation_asset voor de hoe de setup werkt
