### ISSUE TITLE
Personal x --> My x (S)

### ISSUE THREAD

**Issue by PeterNobels** [Kalipo-BV/kalipo-core#926]
# User story specification (one liner)
As a user I want to have the feeling of a personal touch when I use Kalipo so that my connection with Kalipo is strengthened.

# Acceptance criteria

**Functionality**
- [ ] "Personal Autons" --> "My Autons"
- [ ] "Personal Proposals" --> "My Proposals"
- [ ] "Personal Votes" -->  "My Votes" 
- [ ] "Personal POAs" --> "My POAs"

# Deliverables
- [ ] Adjusted User pages

# Estimated work
1 days

**Comment by stellardynamic** [comment]
This is not an issue for Kalipo-core, the problem is solved in the web-ui. I've already proposed the fix as a pull request see here:

https://github.com/Kalipo-BV/kalipo-web3-ui/pull/91
